ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
FROM docker.elastic.co/kibana/kibana:6.4.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
