ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
# FROM docker.elastic.co/kibana/kibana:6.4.2
# FROM docker.elastic.co/kibana/kibana:5.5.3
FROM docker.elastic.co/kibana/kibana:latest

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
