ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
# FROM docker.elastic.co/logstash/logstash:5.5.3
FROM docker.elastic.co/logstash/logstash:6.4.2


# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
